<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\comments\assets
 * @category   CategoryName
 */

namespace open20\amos\comments\assets;

use yii\web\AssetBundle;

/**
 * Class CommentsAsset
 * @package open20\amos\comments\assets
 */
class CommentsAsset extends AssetBundle
{
    /**
     * @inheritdoc
     */
    public $sourcePath = '@vendor/open20/amos-comments/src/assets/web';

    /**
     * @inheritdoc
     */
    public $css = [
        'less/comments.less',
        'less/comments_design_bi.less',
    ];

    /**
     * @inheritdoc
     */
    public $js = [
        'js/comments.js'
    ];

    /**
     * @inheritdoc
     */
    public $depends = [
        'yii\web\JqueryAsset',
    ];

    public function init()
    {
        $moduleL = \Yii::$app->getModule('layout');
        if (!empty($moduleL)) {
            $this->depends [] = 'open20\amos\layout\assets\BaseAsset';
        } else {
            $this->depends [] = 'open20\amos\core\views\assets\AmosCoreAsset';
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}
